name: cupertino_duration_picker
description: cupertino_duration_picker is a duration picker inspired by the Google duration picker.
version: 0.1.1
homepage: https://github.com/zvikarp/cupertino_duration_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  numberpicker: ^2.1.1
  widgetpicker: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter